import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import { ServerIpProvider } from './backendIpContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <ServerIpProvider>
        <body className={`inter.className flex h-screen`}>
          <Navbar />
          {children}
        </body>
      </ServerIpProvider>
    </html>
  )
}
